### PR TITLE
Chore/moves to yml

### PR DESCRIPTION
**Pull request by paulodiovani**
I am planning to make a Portuguese version of this bot, so I had to first make it slightly better to translate.

This PR put all the moves into a YAML file, which Is much easier to read and maintain.
It also:

- add a `requirements.txt`
- remove duplicate moves by using Yaml aliases

### CODE REVIEW

**Comment by rpgmik** [comment]
Thanks @paulodiovani - I'll need to test these locally before merging and deploying.  Good luck with the translation!

**Comment by paulodiovani** [comment]
FYI, The translation is happening in https://github.com/paulodiovani/kult-move-bot-ptbr,
I've also did some other changes like use ENV vars and add a `Procfile` to deploy on Heroku. People in Discord requested a shorted trigger, so I'm considering to have a bang (!) trigger for each move (e.g. `!hoh` instead of `!move hoh`).

If you have interest in the changes, I can make it support multiple languages and we can join the code of the bots.

**Comment by rpgmik** [comment]
Great to hear that things are moving ahead.
Before you go too far down the line of tailoring the translation to this bot though, you should take a look at the new one that just appeared on the Kult - Elysium discord server (created by Mattifier).
It is more sophisticated than this one, and will probably end up replacing it.
Mattifier has shared his JSON code with me (it is very nicely formatted, and provides a lot of additional functionality) and it shouldn’t be too hard to map your translated yaml to the format that he has used.  Ping me (@mik) on the discord server if you want to chat.  Might also be useful to set up a separate discord server to chat about this stuff with Mattifier.

**Comment by rpgmik** [comment]
@paulodiovani - not sure if you've had a chance to look at Mattifier's bot yet (see above), but I'd still be keen to work with you on creating a multi-language bot (for whichever bot version we end up choosing). Ping me on discord (@mik on the kult-elysium server) if you want to have a chat about this.

**Comment by paulodiovani** [comment]
> Great to hear that things are moving ahead.
> Before you go too far down the line of tailoring the translation to this bot though, you should take a look at the new one that just appeared on the Kult - Elysium discord server (created by Mattifier).
> It is more sophisticated than this one, and will probably end up replacing it.
> Mattifier has shared his JSON code with me (it is very nicely formatted, and provides a lot of additional functionality) and it shouldn’t be too hard to map your translated yaml to the format that he has used. Ping me (@mik) on the discord server if you want to chat. Might also be useful to set up a separate discord server to chat about this stuff with Mattifier.

Oh, that is nice.
Is this new bot open source? Can you point me to its repository?

**Comment by paulodiovani** [comment]
> @paulodiovani - not sure if you've had a chance to look at Mattifier's bot yet (see above), but I'd still be keen to work with you on creating a multi-language bot (for whichever bot version we end up choosing). Ping me on discord (@mik on the kult-elysium server) if you want to have a chat about this.

Nice!
There are still a couple things I want to fix, like better support for modifiers (e.g. `+1` works, but `+ 1` (with space) or (`+1 -2`) doesn't) before addressing multi-language.

Multi-language shall be easy now either way. Just a way to decide which YAML to choose from, an ENV var is my preferred choice.

**Comment by rpgmik** [comment]
@paulodiovani - RE the new bot, Mattifier hasn't put his code on GitHub yet, although he said he is going to at some point.  There are still a lot of people using the KultMoveBot though, so I'm going to keep supporting it for now - I see you've popped up on the support discord.  :)

**Pull request merged**
